/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conferencemanagementsystem;

import static conferencemanagementsystem.MainClass.db;
import static conferencemanagementsystem.MainClass.utente;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author salvatore
 */
public class AutoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form AutoreForm_Sottometti
     */
    public AutoreFrame() {
        initComponents();
        if (controllaAmmesso() == false) {
            sottomettiRivisto.setEnabled(false);
        }
        if (controllaPresenzaArticoli() == false) {
            listaArticoli.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaArticoli = new javax.swing.JButton();
        sottomettiRivisto = new javax.swing.JButton();
        sottomettiArticolo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaArticoli.setText("Lista Articoli");
        listaArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaArticoliActionPerformed(evt);
            }
        });

        sottomettiRivisto.setText("Sottometti Articolo Rivisto");
        sottomettiRivisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sottomettiRivistoActionPerformed(evt);
            }
        });

        sottomettiArticolo1.setText("Sottometti Articolo");
        sottomettiArticolo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sottomettiArticolo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaArticoli, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sottomettiRivisto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sottomettiArticolo1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sottomettiArticolo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaArticoli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sottomettiRivisto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaArticoliActionPerformed
        Autore_ListaArticoliSottomessiiFrame lista = new Autore_ListaArticoliSottomessiiFrame();
        lista.setDefaultCloseOperation(HIDE_ON_CLOSE);
        lista.setVisible(true);
    }//GEN-LAST:event_listaArticoliActionPerformed

    private void sottomettiRivistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sottomettiRivistoActionPerformed
        Autore_SottomettiRivistoFrame sottomettiRivistoF = new Autore_SottomettiRivistoFrame();
        sottomettiRivistoF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sottomettiRivistoF.setVisible(true);
    }//GEN-LAST:event_sottomettiRivistoActionPerformed

    private void sottomettiArticolo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sottomettiArticolo1ActionPerformed
      Autore_SottomettiFrame sottomettiF = new Autore_SottomettiFrame();
      sottomettiF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      sottomettiF.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_sottomettiArticolo1ActionPerformed
    
    private boolean controllaAmmesso() {
        String sql = "SELECT * FROM articoli WHERE idUtente = ? and ammesso = true";
        PreparedStatement stat;
        try {
            stat = db.getDBConnection().prepareStatement(sql);
            stat.setInt(1, utente.getId());
            
            ResultSet result = stat.executeQuery();
            
            if(result.next()) {
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Autore_SottomettiRivistoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    private boolean controllaPresenzaArticoli() {
        String sql = "SELECT * FROM articoli WHERE idUtente = ?";
        PreparedStatement stat;
        try {
            stat = db.getDBConnection().prepareStatement(sql);
            stat.setInt(1, utente.getId());
            
            ResultSet result = stat.executeQuery();
            
            if(result.next()) {
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Autore_SottomettiRivistoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton listaArticoli;
    private javax.swing.JButton sottomettiArticolo1;
    private javax.swing.JButton sottomettiRivisto;
    // End of variables declaration//GEN-END:variables
}
