/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conferencemanagementsystem;

import static conferencemanagementsystem.MainClass.db;
import static conferencemanagementsystem.MainClass.scadutaReview;
import static conferencemanagementsystem.MainClass.utente;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author salvatore
 */
public class RecensoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form RecensoreFrame
     */
    public RecensoreFrame() {
        initComponents();
        if (isAutore() == true) {
            partecipa.setEnabled(false);
            pannelloAutore.setEnabled(true);
        } else {
            partecipa.setEnabled(true);
            pannelloAutore.setEnabled(false);
        }
        if (scadutaReview = true) {
            sottomettiRecensione.setEnabled(false);
            invitaSottorecensore.setEnabled(false);
        }
    }
    
    
    private boolean isAutore() {
        boolean test = false;
        
        String sql = "SELECT * FROM autori WHERE idUtente = ?";
        PreparedStatement stat;
        try {
            stat = db.getDBConnection().prepareStatement(sql);
            stat.setInt(1, utente.getId());
            
            ResultSet result = stat.executeQuery();
            if(result.next()) {
                test = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Autore_SottomettiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return test;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaArticoli = new javax.swing.JToggleButton();
        invitaSottorecensore = new javax.swing.JToggleButton();
        sottomettiRecensione = new javax.swing.JToggleButton();
        partecipa = new javax.swing.JToggleButton();
        pannelloAutore = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaArticoli.setText("Lista Articoli");
        listaArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaArticoliActionPerformed(evt);
            }
        });

        invitaSottorecensore.setText("Invita Sottorecensore");
        invitaSottorecensore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invitaSottorecensoreActionPerformed(evt);
            }
        });

        sottomettiRecensione.setText("Sottometti Recensione");
        sottomettiRecensione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sottomettiRecensioneActionPerformed(evt);
            }
        });

        partecipa.setText("Partecipa come Autore");
        partecipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partecipaActionPerformed(evt);
            }
        });

        pannelloAutore.setText("Pannello Autore");
        pannelloAutore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pannelloAutoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaArticoli, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invitaSottorecensore, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sottomettiRecensione, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partecipa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pannelloAutore, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaArticoli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partecipa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sottomettiRecensione, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pannelloAutore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(invitaSottorecensore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sottomettiRecensioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sottomettiRecensioneActionPerformed
        Recensore_SottomettiRecensioneFrame sottomettiF = new Recensore_SottomettiRecensioneFrame();
        sottomettiF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sottomettiF.setVisible(true);
    }//GEN-LAST:event_sottomettiRecensioneActionPerformed

    private void invitaSottorecensoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invitaSottorecensoreActionPerformed
        Recensore_InvitaSottoRecensoreFrame invitaF = new Recensore_InvitaSottoRecensoreFrame();
        invitaF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        invitaF.setVisible(true);
    }//GEN-LAST:event_invitaSottorecensoreActionPerformed

    private void listaArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaArticoliActionPerformed
       
        Recensore_AccettaArticoliAssegnatiFrame articoliF = new Recensore_AccettaArticoliAssegnatiFrame();
        articoliF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        articoliF.setVisible(true);
    }//GEN-LAST:event_listaArticoliActionPerformed

    private void partecipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partecipaActionPerformed
      Autore_SottomettiFrame sottomettiF = new Autore_SottomettiFrame();
      sottomettiF.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      sottomettiF.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_partecipaActionPerformed

    private void pannelloAutoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pannelloAutoreActionPerformed
        AutoreFrame autore = new AutoreFrame();
        autore.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        autore.setVisible(true);
    }//GEN-LAST:event_pannelloAutoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecensoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecensoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecensoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecensoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecensoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton invitaSottorecensore;
    private javax.swing.JToggleButton listaArticoli;
    private javax.swing.JToggleButton pannelloAutore;
    private javax.swing.JToggleButton partecipa;
    private javax.swing.JToggleButton sottomettiRecensione;
    // End of variables declaration//GEN-END:variables
}
